### ISSUE TITLE
pyDal changes Row()

### ISSUE THREAD

**Issue by grutz** [KvasirSecurity/Kvasir#173]
Recently DAL was separated from web2py into https://github.com/web2py/pydal. This changes some "unsupported" methods Kvasir uses. 

Only two instances are used in valkyries (web and vnc screenshots). Should be changed to:

```
try:
    from pydal.objects import Row
except ImportError:
    from gluon.dal import Row
```

**Comment by RCStep** [comment]
Changing line 88 to the following fixes webimaging.py for the separate pydal install.
```
from gluon.dal.objects import Row
```

**Comment by grutz** [comment]
Thanks, forgot I hadn't merged this yet!
