### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by viks1234** [KvasirSecurity/Kvasir#43]
Hi all
 I have installed the application as given in wiki. But when I try to log in I get error " Registration needs Verification "   How do I verify it. Please help

**Comment by jcmoreno** [comment]
Hi I'm having the same problem. I updated the records with the "Registration Id" and tried adding new records with the "Registration Id" but I keep getting "Registration needs Verification". Now if I run something like: 
./web2py.py -R applications/kvasir/private/user.py -S kvasir -M -A -u admin3 -p <password>

The script will output:
"web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2015
Version 2.12.3-stable+timestamp.2015.08.18.19.14.07
Database drivers available: psycopg2, pymysql, imaplib, MySQLdb, pg8000, sqlite3, sqlite2, pymongo

Kvasir User Add/Modify Management

Adding admin3 to Kvasir user database..."

However the user does not get added to the table, and if I try to login in with admin3 I get "Invalid login".

Please assist. Thank you.

**Comment by grutz** [comment]
After https://github.com/KvasirSecurity/Kvasir/blob/master/models/db.py#L52 add this:

```
auth.settings.registration_requires_verification=False
```

You shouldn't need to hack up the web2py code: http://web2py.com/books/default/chapter/29/09/access-control

**Comment by jcmoreno** [comment]
Hi grutz,

Thank you for your response. I restored the backup of the gluon/tools.py and added this setting in the /opt/Kvasir/models/db.py as shown below, but no luck.

auth.settings.hmac_key = settings.kvasir_config.get('security_key') # before define_tables()
auth.settings.actions_disabled = [ 'register', 'request_reset_password', 'retrieve_username' ]
auth.settings.allow_basic_login=True
**auth.settings.registration_requires_verification=False**
#crud.settings.auth = auth                      # =auth to enforce authorization on crud
current.auth = auth

**Comment by grutz** [comment]
Based on the access-control documentation (http://web2py.com/books/default/chapter/29/09/access-control#Auth-Settings-and-messages) we may also need:

```
auth.settings.registration_requires_verification=False
auth.settings.registration_requires_approval=False
```

If these still don't work then make sure you have any value in the user's Registration Id field through the admin panel.

**Comment by mfh17** [comment]
I’ve added both setting above, and created a new user with a registration ID, but it still doesn’t work; i still get a ‘registration needs verification’ alert
